#!/bin/bash

source ~/.bashrc

#SWIFT_PATH=/home/amr/swift
#PATH=/home/amr/resources/git-plus:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

PARAM=x$1
PARAM2=x$2
cd $SWIFT_PATH

if [ ${PARAM} = "x-c" ] ; then
echo ========== Cleaning ===========
rm -rf build
rm -f swift/*.tar.gz
fi

if [ ${PARAM2} = "x-u" ] ; then
echo ========== Syncing ==========
git multi pull
git multi fetch apple
git multi merge apple/master
fi

echo ========== Running script ==========
./swift/utils/build-toolchain local.swift || exit

echo ========== Finishing ==========
cd $SWIFT_PATH
test -e swift/swift-nightly-install || exit 
rm -rf toolchains/swift-toolchain-$(date "+%u")
mv toolchains/swift-toolchain toolchains/swift-toolchain-$(date "+%u")
cp -r swift/swift-nightly-install toolchains/swift-toolchain

