#!/bin/bash

source ~/.bashrc
#export SWIFT_PATH=~/swift
#export PATH=/home/amr/resources/git-plus:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

PARAM=x$1
PARAM2=x$2
cd $SWIFT_PATH

if [ ${PARAM} = "x-c" ] ; then
echo ========== Cleaning ===========
rm -rf build/buildbot_linux
rm -f swift/*.tar.gz
fi

if [ ${PARAM} = "x-u" ] || [ ${PARAM2} = "x-u" ] ; then
echo ========== Syncing ==========
git multi pull
git multi fetch upstream
git multi merge upstream/master
fi

echo ========== Running script ==========
./swift/utils/build-toolchain local.swift || exit

echo ========== Finishing ==========
cd $SWIFT_PATH
test -e swift/swift-nightly-install || exit 
rm -rf ~/backup/swift-toolchain-$(date "+%u")
cp swift-toolchain ~/backup/swift-toolchain-$(date "+%u")
cp -r swift/swift-nightly-install swift-toolchain
