#!/bin/bash

source ~/.bashrc

PARAM=x$1
PARAM2=x$2
cd $SWIFT_PATH

if [ ${PARAM} = "x-c" ] ; then
echo ========== Cleaning ===========
rm -rf build/Ninja-ReleaseAssert
fi

if [ ${PARAM} = "x-u" ] || [ ${PARAM2} = "x-u" ] ; then
echo ========== Syncing ==========
git multi pull
git multi fetch apple
git multi merge apple/master
fi

echo ========== Running script ==========
./swift/utils/android/build-toolchain || exit

echo ========== Finishing ==========
cd $SWIFT_PATH

test -e swift-android-toolchain || exit
rm -rf toolchains/swift-android-toolchain-$(date "+%u")
cp swift-android-toolchain toolchains/swift-android-toolchain-$(date "+%u")

