#!/bin/bash

source /home/amr/.bashrc

#SWIFT_PATH=/home/amr/swift
#PATH=/home/amr/resources/git-plus:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PARAM=x$1
PARAM2=x$2
cd $SWIFT_PATH

if [ ${PARAM} = "x-c" ] ; then
echo ========== Cleaning ===========
rm -rf build
rm -f swift/*.tar.gz
fi

if [ ${PARAM2} = "x-u" ] ; then
echo ========== Syncing ==========
git multi pull
git multi fetch upstream
git multi merge upstream/master
fi

echo ========== Running script ==========
./swift/utils/android/build-toolchain || exit

echo ========== Finishing ==========
cd $SWIFT_PATH
test -e swift-android-toolchain || exit 
mkdir -p toolchains/android
rm -rf toolchains/swift-android-toolchain-$(date "+%u")
cp swift-android-toolchain toolchains/swift-android-toolchain-$(date "+%u")

