#!/usr/bin/env bash
#
# android/build-toolchain
#
# This source file is part of the Swift.org open source project
#
# Copyright (c) 2014 - 2017 Apple Inc. and the Swift project authors
# Licensed under Apache License v2.0 with Runtime Library Exception
#
# See https://swift.org/LICENSE.txt for license information
# See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors

set -e

cd "$(dirname $0)/../../.." || exit 1
SWIFT_PATH=$PWD

ANDROID_NDK_PATH="${ANDROID_NDK_PATH:?Please set the Android NDK path in the ANDROID_NDK_PATH environment variable}"
ANDROID_ICU_PATH=${SWIFT_PATH}/libiconv-libicu-android

[ -e ${ANDROID_ICU_PATH} ] || exit 1

SWIFT_ANDROID_TOOLCHAIN_PATH="${SWIFT_PATH}/swift-android-toolchain"
SWIFT_ANDROID_BUILD_PATH="${SWIFT_PATH}/build/Ninja-ReleaseAssert"

rm -rf ${SWIFT_ANDROID_TOOLCHAIN_PATH}

#cp $ANDROID_NDK_PATH/sysroot/usr/include/{ftw,langinfo,netdb,search,syslog,tar,nl_types}.h $ANDROID_NDK_PATH/platforms/android-21/arch-arm/usr/include

${SWIFT_PATH}/swift/utils/build-script \
    -R \
    --android \
    --android-ndk ${ANDROID_NDK_PATH} \
    --android-api-level 21 \
    --android-icu-uc "${ANDROID_ICU_PATH}/armeabi-v7a" \
    --android-icu-uc-include "${ANDROID_ICU_PATH}/armeabi-v7a/icu/source/common" \
    --android-icu-i18n "${ANDROID_ICU_PATH}/armeabi-v7a" \
    --android-icu-i18n-include "${ANDROID_ICU_PATH}/armeabi-v7a/icu/source/i18n" \
    --foundation --install-foundation \
    --llbuild --install-llbuild \
    --lldb --install-lldb \
    --install-swift \
    --swiftpm --install-swiftpm \
    --xctest --install-xctest \
    --install-destdir=${SWIFT_ANDROID_TOOLCHAIN_PATH} || exit

    #'--swift-install-components=autolink-driver;compiler;clang-builtin-headers;stdlib;swift-remote-mirror;sdk-overlay;dev' \

test -e ${SWIFT_ANDROID_TOOLCHAIN_PATH} || exit
test -e ${SWIFT_ANDROID_BUILD_PATH} || exit
cp -r ${SWIFT_ANDROID_BUILD_PATH}/swift-linux-x86_64/{bin,lib,include} ${SWIFT_ANDROID_TOOLCHAIN_PATH}/usr
cp -r ${SWIFT_ANDROID_BUILD_PATH}/swiftpm-linux-x86_64/.bootstrap/lib ${SWIFT_ANDROID_TOOLCHAIN_PATH}/usr

${SWIFT_PATH}/swift-corelibs-libdispatch/build-android
${SWIFT_PATH}/swift-corelibs-foundation/build-android

