#!/bin/bash

set -e

cd "$(dirname $0)/../../.." || exit

rm -r swift-android-toolchain
scp amr@ubuntu16.local:swift/swift-android-toolchain.zip .
unzip swift-android-toolchain.zip
rm swift-android-toolchain.zip
adb push swift-android-toolchain/usr/lib/swift/android/libswiftCore.so /data/local/tmp
adb push swift-android-toolchain/usr/lib/swift/android/libswiftGlibc.so /data/local/tmp
adb push swift-android-toolchain/usr/lib/swift/android/libswiftSwiftOnoneSupport.so /data/local/tmp
adb push swift-android-toolchain/usr/lib/swift/android/libswiftRemoteMirror.so /data/local/tmp
adb push swift-android-toolchain/usr/lib/swift/android/libswiftSwiftExperimental.so /data/local/tmp

