#!/bin/bash

set -e

cd "$(dirname $0)/../../.." || exit

rm -r swift-android-toolchain
scp ${SWIFT_MACHINE_USERNAME}@${SWIFT_MACHINE_ADDRESS}:swift/swift-android-toolchain.zip .
unzip swift-android-toolchain.zip
rm swift-android-toolchain.zip
adb push swift-android-toolchain/usr/lib/swift/android/libswiftCore.so /data/local/tmp
adb push swift-android-toolchain/usr/lib/swift/android/libswiftGlibc.so /data/local/tmp
adb push swift-android-toolchain/usr/lib/swift/android/libswiftSwiftOnoneSupport.so /data/local/tmp
adb push swift-android-toolchain/usr/lib/swift/android/libswiftRemoteMirror.so /data/local/tmp
adb push swift-android-toolchain/usr/lib/swift/android/libswiftSwiftExperimental.so /data/local/tmp

adb push swift-android-toolchain/usr/lib/swift/android/libicudata.so /data/local/tmp
adb push swift-android-toolchain/usr/lib/swift/android/libicui18n.so /data/local/tmp
adb push swift-android-toolchain/usr/lib/swift/android/libicuuc.so /data/local/tmp
adb push ${ANDROID_NDK_DIR}/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libc++_shared.so /data/local/tmp

